print("' ' '")
print("Author: Kegan Firey")
print("KUID: 3176824")
print("Date: 25AUG25")
print("Lab: lab01")
print("Last modified: 25AUG25")
print("Purpose: Code prints a brief description of its creator")
print("' ' '")
print("My name is Kegan Firey")
print("My major is Electrical Engineering") 
print("My hobbies are:")
print("\tPlaying games (board, card, or video)")
print("\t3d Printing")
print("\tReading")
print("Goodbye")
